pipeline {
  agent any 

  stages {
    stage('Checkout') {
      steps { 
        checkout scm
      }
    }
    stage('Build') { 
      steps { 
        sh 'source ~/.bashrc && cd eventservice && npm install'
      }
    }
    stage('Test'){
      steps {
        sh 'source ~/.bashrc && cd eventservice && npm test'
      }
    }
    stage('Container'){
      steps {
        sh 'source ~/.bashrc && cd eventservice && sh build.sh container'
      }
    }
    stage('Deploy'){
      steps {
        sh 'source ~/.bashrc && cd eventservice && sh build.sh deploy'
      }
    }
  }
}

